### ISSUE TITLE
[FEAT] Logging

### ISSUE THREAD

**Issue by 5jisoo** [SMWU-POCHAK/POCHAK-Server#6]
## 📍 구현 기능
- 로깅, 로그 쌓기
- 서버에 들어온 요청/응답, 예외 발생 등에 대해 로그 남기기
- 로그를 파일로 남겨, 추후 배포 중 오류가 발생한 경우를 확인할 수 있도록 함

## 🛠 작업 내용
- [x] AOP 로그 쌓기
- [x] 로컬 - 도커 컨테이너 로그 디렉토리 마운팅
- [x] crontab 로컬에 쌓인 로그 매일 자정 cloud 업로드 설정
- [x] logback.xml을 통해 log rotation은 관리됨 (1일 보관 후 삭제)

## 📢 추가 의논 사항
- 추가적으로 의논할 사항이나 발생한 에러에 대한 설명

## 🚨 주의 사항
- 구현하며 발견한 주의 사항이나 **꼭 확인했으면 하는 로직**에 대한 설명

**Comment by yeahjinjeong** [comment]
<img width="1154" alt="스크린샷 2024-12-20 오후 4 44 43" src="https://github.com/user-attachments/assets/5c4be45c-4d96-479b-8529-d3e2a3a832ca" />

서버에 저장된 로그 파일
