### ISSUE TITLE
[Refactor] Alarm 엔티티 Column 이름 통일

### ISSUE THREAD

**Issue by 5jisoo** [SMWU-POCHAK/POCHAK-Server#93]
## 📍 개선한 기능
Alarm 엔티티 Column 이름 통일
LikedAlarm 에서는 likedPostId이고.. 다른곳에서는 postId임 DB 컬럼 이름만이라도 통일을 시켜줘야될듯

## 🛠 개선 작업 내용
- [x] 컬럼 이름 통일 (코드 변경)
- [x] DB 적용 + 기존 데이터 옮기기

**Comment by dudrhy12** [comment]
좋은 생각입니다...... 헷갈려~!

**Comment by yeahjinjeong** [comment]
@Entity
@Getter
@AllArgsConstructor
@NoArgsConstructor(access = PROTECTED)
@SQLDelete(sql = "UPDATE like_entity SET status = 'DELETED' WHERE id = ?")
public class LikeEntity extends BaseEntity {
    @Id
    @GeneratedValue(strategy = IDENTITY)
    private Long id;

    @ManyToOne(fetch = LAZY)
    @JoinColumn(name = "like_member_id")
    private Member likeMember;

    @ManyToOne(fetch = LAZY)
    @JoinColumn(name = "liked_post_id")
    private Post likedPost;

    @Builder
    public LikeEntity(Member likeMember, Post likedPost) {
        this.likeMember = likeMember;
        this.likedPost = likedPost;
    }
}

LikeEntity도 수정할까요?
